### PR TITLE
Use Dot product and Swizzle instead of multiplying and adding elements

### PR DESCRIPTION
**Pull request by benanil**
area calculation is better with dot product, same thing can be done in kd tree calculation as well.

### CODE REVIEW

**Comment by benanil** [comment]
@jbikker ?

**Review by jbikker — APPROVED** [review]

**Comment by jbikker** [comment]
Thanks for the pull request, merged!

**Comment by jbikker** [comment]
Quick question: Did you measure the performance of this approach? Simply summing the three floats appears to be faster in my experiments.

**Comment by benanil** [comment]
> Quick question: Did you measure the performance of this approach? Simply summing the three floats appears to be faster in my experiments.

No I haven't measured.

**Comment by benanil** [comment]
We can use SIMD with CalculateNodeCost function too.
it can be done with 1 subtraction, 1 swizzle,  1 masking, 1 dot pruduct and 1 multiply.

Technically these should be faster idk why your experiments are exact opposite.
(compiler, debug or release etc. lots of different facts)

My PR looks more clear too because we are not using MSVC only m128_f32[n] things.
```
struct BVHNode
{
	union { struct { float3 aabbMin; uint leftFirst; }; __m128 aabbMin4; };
	union { struct { float3 aabbMax; uint triCount; }; __m128 aabbMax4; };
	bool isLeaf() const { return triCount > 0; } // empty BVH leaves do not exist
	float CalculateNodeCost()
	{
		float3 e = aabbMax - aabbMin; // extent of the node
		return (e.x * e.y + e.y * e.z + e.z * e.x) * triCount;
	}
};
```

**Comment by jbikker** [comment]
I am sorry, but you really need to measure performance for this one. Doing
a union may yield the same performance as the m128_f32 'array' but that's
not guaranteed at all: According to the C++ standard the union forces the
struct to be in memory, while the m128_f32 approach allows for the data to
be in a register. Only a profiling run can give a definite answer here.

- Jacco.

**Comment by benanil** [comment]
@jbikker 
I found the problem!
As you said m128_f32 are in the register, that makes 3 mul and 2 add for dot product
since my swizzle function is not efficient it doesn't improve the performace
#define VecSwizzleMask(vec, mask)    _mm_castsi128_ps(_mm_shuffle_epi32(_mm_castps_si128(vec), mask))

we can use _mm_shuffle_ps instruction instead. 
I will measure with this instruction and probably send new pr.

**Comment by benanil** [comment]
image
latency and troughput of this instruction is good, and should be better

**Comment by jbikker** [comment]
I got to something like this earlier:

const __m128 v = _mm_mul_ps( q, _mm_shuffle_ps( q, q, 9 ) );
return v.m128_f32[0] + v.m128_f32[1] + v.m128_f32[2];

which can be done without the per-element access like this:

const __m128 v1 = _mm_shuffle_ps( v, v, _MM_SHUFFLE( 1, 1, 1, 1 ) );
const __m128 v2 = _mm_movehl_ps( v, v );
return _mm_cvtss_f32( _mm_add_ps( v, _mm_add_ps( v1, v2 ) ) );

Sadly even with that the first approach is (slightly) faster, at least in msvc.

**Comment by benanil** [comment]
I'm going to do something like this
_mm_cvtss_f32(_mm_dp_ps(q, _mm_shuffle_ps( q, q, 9 ), 0x7f))

**Comment by jbikker** [comment]
Do note that _mm_dp_ps is expensive.

**Comment by benanil** [comment]
created new pr

**Pull request merged**
