### PR TITLE
small changes

### PR DESCRIPTION
**Pull request by dparnell**
Hi,

  I have really enjoyed reading through your articles. While playing with the code on my less than meaty laptop I found I could not run the GPU accelerated code at anything more that a frame every few seconds so I modified it to allow for smaller numbers of dragons in the scene.

Thank you for making this information available in an easy to understand and concise manner :)

Daniel

### CODE REVIEW

**Comment by jbikker** [comment]
Doesn't it make more sense to simply reduce the screen resolution? It's a BVH; in principle triangle count should not affect performance all that much. What kind of performance difference are you seeing at various SKIP values?

**Comment by dparnell** [comment]
I'm not seeing much difference when I make the window smaller. Even at 640 x 480 it still runs very slowly on my machine. It's odd but reducing the number of dragons makes it work at a decent speed.

**Comment by dparnell** [comment]
Dropping it to 320 x 200 allows it to work at between 10 to 20 FPS

**Comment by dparnell** [comment]
I'm running an NVidia Quadro M620, so I would have thought it should have been able to handle the load, but I guess not

**Comment by jbikker** [comment]
Well it is a pretty intense scene, and the code is not really optimized, it has been written mostly for clarity.
I looked up your GPU: in Geekbench and Passmark it has roughly half the performance of a 1050, which is not a lot. I can imagine it struggles with the demos.

**Pull request closed without merging**
